In [1]:
#创建相关系数矩阵
relation = [[0] * 10] * 10
for r in relation:
    print(r)

#但是这并不是正确的构建方法因为此方法构造的二维数组是对[]*n引用了m次，更改其中一行的值会导致每行的值都被更改导致最后的结果每行相同

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [2]:
#这是正确的构造
import numpy as np
mat = np.zeros((10, 10))
relationMat = mat.astype(int)
print(relationMat)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [3]:
#设置打印格式
np.set_printoptions(
    formatter={'int': '{:5d}'.format},  # 5 字符宽度，十进制整数
    linewidth=100  # 避免自动换行
)

In [4]:
with open("./whc.csv","r",encoding="utf-8") as f:
    s = f.read()
    #print(s)

In [5]:
rows = s.split('\n')
#for r in rows:
    #print(r)

In [6]:
for row in rows:
    dataArr = row.split(',')
    #print(dataArr)
    for i in range(1,11):
        try:
            if dataArr[i] == '1':
                relationMat[i-1][i-1] += 1
            for j in range(i+1,11):
                if dataArr[i] == '1':
                    if dataArr[j] == '1':
                        relationMat[i-1][j-1] += 1
                        relationMat[j-1][i-1] += 1
        except IndexError:
            print(str(i) + "索引超出范围！" + row)
        

1索引超出范围！
2索引超出范围！
3索引超出范围！
4索引超出范围！
5索引超出范围！
6索引超出范围！
7索引超出范围！
8索引超出范围！
9索引超出范围！
10索引超出范围！


In [11]:
#为什么会报错？因为string.split('\n')会在结尾多生成一个空白行row

#验证
print(len(rows))
#输出为1224，而实际上只有1223条有效数据

#debug时寻找报错行困难，以后使用迭代器方便查找index

1224


In [7]:
for r in relationMat:
    print(r)

[  261   146   133   172    17    82     9     1     4     4]
[  146   479   204   343    55   122     4     0     2     3]
[  133   204   513   264    84   136    18     6    16    16]
[  172   343   264   641    84   141     8     3     6     8]
[   17    55    84    84   172    26    12     4     4     4]
[   82   122   136   141    26   256     9     4     5     8]
[    9     4    18     8    12     9   151    63    71    83]
[    1     0     6     3     4     4    63    98    34    35]
[    4     2    16     6     4     5    71    34   137   106]
[    4     3    16     8     4     8    83    35   106   168]


In [8]:
with open('./whc.json','w',encoding = 'utf-8') as f:
    f.write('{\n'+'\"nodes:\":[\n')
    for i in range(0,9):
        f.write('{\"id\": \"' + str(i) + '\", \"category\": 1, \"symbolSize\": ' + str(relationMat[i][i]) + '},\n')
    f.write('{\"id\": \"' + str(9) + '\", \"category\": 1, \"symbolSize\": ' + str(relationMat[9][9]) + '}\n')
    f.write('],\n')
    
    f.write('\"links:\":[\n')
    for i in range(0,10):
        for j in range (i+1,10):
            if i == 9 and j == 9:
                continue
            else:
                f.write('{\"source\": ' + str(i) + ', \"target\": ' + str(j) + ', \"value\": \"' + str(relationMat[i][j]) + '\"},\n')
    f.write('{\"source\": ' + str(9) + ', \"target\": ' + str(9) + ', \"value\": \"' + str(relationMat[9][9]) + '\"}\n')
    f.write('],\n')
    
    f.write('\"categories:\":[\n')
    f.write(']}\n')